TST: Freeze the pip version
Pip 20.3 has issues with handling the CAT/data-CAT dependency chain:

ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/user_guide/#fixing-conflicting-dependencies

The conflict is caused by:
    cat[test] 0.9.11 depends on cat 0.9.11 (from /home/runner/work/CAT/CAT)
    data-cat 0.5.2 depends on cat 0.9.11 (from git+https://github.com/nlesc-nano/CAT)

To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip attempt to solve the dependency conflict